#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : alsa-firmware
Version  : 1.0.29
Release  : 2
URL      : ftp://ftp.alsa-project.org/pub/firmware/alsa-firmware-1.0.29.tar.bz2
Source0  : ftp://ftp.alsa-project.org/pub/firmware/alsa-firmware-1.0.29.tar.bz2
Summary  : ALSA firmware package
Group    : Development/Tools
License  : GPL-2.0
Requires: alsa-firmware-data = %{version}-%{release}
Requires: alsa-firmware-license = %{version}-%{release}

%description
GENERAL
=======
This package contains the firmware binaries for each loader program
included in alsa-tools package.  The firmware data can be used by each
ALSA firmware loader program like vxloader, or passed through the
hotplug firmware-loading mechanism.

%package data
Summary: data components for the alsa-firmware package.
Group: Data

%description data
data components for the alsa-firmware package.


%package license
Summary: license components for the alsa-firmware package.
Group: Default

%description license
license components for the alsa-firmware package.


%prep
%setup -q -n alsa-firmware-1.0.29

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554126450
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1554126450
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/alsa-firmware
cp COPYING %{buildroot}/usr/share/package-licenses/alsa-firmware/COPYING
%make_install

%files
%defattr(-,root,root,-)
/lib/firmware/aica_firmware.bin
/lib/firmware/asihpi/dsp5000.bin
/lib/firmware/asihpi/dsp6200.bin
/lib/firmware/asihpi/dsp6205.bin
/lib/firmware/asihpi/dsp6400.bin
/lib/firmware/asihpi/dsp6600.bin
/lib/firmware/asihpi/dsp8700.bin
/lib/firmware/asihpi/dsp8900.bin
/lib/firmware/cs46xx/ba1
/lib/firmware/cs46xx/cwc4630
/lib/firmware/cs46xx/cwcasync
/lib/firmware/cs46xx/cwcbinhack
/lib/firmware/cs46xx/cwcdma
/lib/firmware/cs46xx/cwcsnoop
/lib/firmware/ctefx.bin
/lib/firmware/ctspeq.bin
/lib/firmware/digiface_firmware.bin
/lib/firmware/digiface_firmware_rev11.bin
/lib/firmware/ea/3g_asic.fw
/lib/firmware/ea/darla20_dsp.fw
/lib/firmware/ea/darla24_dsp.fw
/lib/firmware/ea/echo3g_dsp.fw
/lib/firmware/ea/gina20_dsp.fw
/lib/firmware/ea/gina24_301_asic.fw
/lib/firmware/ea/gina24_301_dsp.fw
/lib/firmware/ea/gina24_361_asic.fw
/lib/firmware/ea/gina24_361_dsp.fw
/lib/firmware/ea/indigo_dj_dsp.fw
/lib/firmware/ea/indigo_djx_dsp.fw
/lib/firmware/ea/indigo_dsp.fw
/lib/firmware/ea/indigo_io_dsp.fw
/lib/firmware/ea/indigo_iox_dsp.fw
/lib/firmware/ea/layla20_asic.fw
/lib/firmware/ea/layla20_dsp.fw
/lib/firmware/ea/layla24_1_asic.fw
/lib/firmware/ea/layla24_2A_asic.fw
/lib/firmware/ea/layla24_2S_asic.fw
/lib/firmware/ea/layla24_dsp.fw
/lib/firmware/ea/loader_dsp.fw
/lib/firmware/ea/mia_dsp.fw
/lib/firmware/ea/mona_2_asic.fw
/lib/firmware/ea/mona_301_1_asic_48.fw
/lib/firmware/ea/mona_301_1_asic_96.fw
/lib/firmware/ea/mona_301_dsp.fw
/lib/firmware/ea/mona_361_1_asic_48.fw
/lib/firmware/ea/mona_361_1_asic_96.fw
/lib/firmware/ea/mona_361_dsp.fw
/lib/firmware/emu/audio_dock.fw
/lib/firmware/emu/emu0404.fw
/lib/firmware/emu/emu1010_notebook.fw
/lib/firmware/emu/emu1010b.fw
/lib/firmware/emu/hana.fw
/lib/firmware/emu/micro_dock.fw
/lib/firmware/ess/maestro3_assp_kernel.fw
/lib/firmware/ess/maestro3_assp_minisrc.fw
/lib/firmware/korg/k1212.dsp
/lib/firmware/mixart/miXart8.elf
/lib/firmware/mixart/miXart8.xlx
/lib/firmware/mixart/miXart8AES.xlx
/lib/firmware/multiface_firmware.bin
/lib/firmware/multiface_firmware_rev11.bin
/lib/firmware/pcxhr/b321_512.b56
/lib/firmware/pcxhr/d321_512.d56
/lib/firmware/pcxhr/dspb1222e.b56
/lib/firmware/pcxhr/dspb1222hr.b56
/lib/firmware/pcxhr/dspb882e.b56
/lib/firmware/pcxhr/dspb882hr.b56
/lib/firmware/pcxhr/dspb924.b56
/lib/firmware/pcxhr/dspd1222.d56
/lib/firmware/pcxhr/dspd222.d56
/lib/firmware/pcxhr/dspd882.d56
/lib/firmware/pcxhr/dspe882.e56
/lib/firmware/pcxhr/dspe924.e56
/lib/firmware/pcxhr/e321_512.e56
/lib/firmware/pcxhr/xc_1_882.dat
/lib/firmware/pcxhr/xi_1_882.dat
/lib/firmware/pcxhr/xlxc1222e.dat
/lib/firmware/pcxhr/xlxc1222hr.dat
/lib/firmware/pcxhr/xlxc222.dat
/lib/firmware/pcxhr/xlxc882e.dat
/lib/firmware/pcxhr/xlxc882hr.dat
/lib/firmware/pcxhr/xlxc924.dat
/lib/firmware/pcxhr/xlxint.dat
/lib/firmware/rpm_firmware.bin
/lib/firmware/sb16/alaw_main.csp
/lib/firmware/sb16/ima_adpcm_capture.csp
/lib/firmware/sb16/ima_adpcm_init.csp
/lib/firmware/sb16/ima_adpcm_playback.csp
/lib/firmware/sb16/mulaw_main.csp
/lib/firmware/turtlebeach/msndinit.bin
/lib/firmware/turtlebeach/msndperm.bin
/lib/firmware/turtlebeach/pndsperm.bin
/lib/firmware/turtlebeach/pndspini.bin
/lib/firmware/vx/bd56002.boot
/lib/firmware/vx/bd563s3.boot
/lib/firmware/vx/bd563v2.boot
/lib/firmware/vx/bx_1_vp4.b56
/lib/firmware/vx/bx_1_vxp.b56
/lib/firmware/vx/l_1_v22.d56
/lib/firmware/vx/l_1_vp4.d56
/lib/firmware/vx/l_1_vx2.d56
/lib/firmware/vx/l_1_vxp.d56
/lib/firmware/vx/x1_1_vp4.xlx
/lib/firmware/vx/x1_1_vx2.xlx
/lib/firmware/vx/x1_1_vxp.xlx
/lib/firmware/vx/x1_2_v22.xlx
/lib/firmware/yamaha/ds1_ctrl.fw
/lib/firmware/yamaha/ds1_dsp.fw
/lib/firmware/yamaha/ds1e_ctrl.fw
/lib/firmware/yamaha/yss225_registers.bin

%files data
%defattr(-,root,root,-)
/usr/share/alsa/firmware/hdsploader/digiface_firmware.bin
/usr/share/alsa/firmware/hdsploader/digiface_firmware_rev11.bin
/usr/share/alsa/firmware/hdsploader/multiface_firmware.bin
/usr/share/alsa/firmware/hdsploader/multiface_firmware_rev11.bin
/usr/share/alsa/firmware/hdsploader/rpm_firmware.bin
/usr/share/alsa/firmware/mixartloader/miXart.conf
/usr/share/alsa/firmware/mixartloader/miXart8.elf
/usr/share/alsa/firmware/mixartloader/miXart8.xlx
/usr/share/alsa/firmware/mixartloader/miXart8AES.xlx
/usr/share/alsa/firmware/pcxhrloader/b321_512.b56
/usr/share/alsa/firmware/pcxhrloader/d321_512.d56
/usr/share/alsa/firmware/pcxhrloader/dspb1222e.b56
/usr/share/alsa/firmware/pcxhrloader/dspb1222hr.b56
/usr/share/alsa/firmware/pcxhrloader/dspb882e.b56
/usr/share/alsa/firmware/pcxhrloader/dspb882hr.b56
/usr/share/alsa/firmware/pcxhrloader/dspb924.b56
/usr/share/alsa/firmware/pcxhrloader/dspd1222.d56
/usr/share/alsa/firmware/pcxhrloader/dspd222.d56
/usr/share/alsa/firmware/pcxhrloader/dspd882.d56
/usr/share/alsa/firmware/pcxhrloader/dspe882.e56
/usr/share/alsa/firmware/pcxhrloader/dspe924.e56
/usr/share/alsa/firmware/pcxhrloader/e321_512.e56
/usr/share/alsa/firmware/pcxhrloader/pcxhr.conf
/usr/share/alsa/firmware/pcxhrloader/pcxhr0.conf
/usr/share/alsa/firmware/pcxhrloader/pcxhr1.conf
/usr/share/alsa/firmware/pcxhrloader/pcxhr2.conf
/usr/share/alsa/firmware/pcxhrloader/pcxhr3.conf
/usr/share/alsa/firmware/pcxhrloader/pcxhr4.conf
/usr/share/alsa/firmware/pcxhrloader/pcxhr5.conf
/usr/share/alsa/firmware/pcxhrloader/xc_1_882.dat
/usr/share/alsa/firmware/pcxhrloader/xi_1_882.dat
/usr/share/alsa/firmware/pcxhrloader/xlxc1222e.dat
/usr/share/alsa/firmware/pcxhrloader/xlxc1222hr.dat
/usr/share/alsa/firmware/pcxhrloader/xlxc222.dat
/usr/share/alsa/firmware/pcxhrloader/xlxc882e.dat
/usr/share/alsa/firmware/pcxhrloader/xlxc882hr.dat
/usr/share/alsa/firmware/pcxhrloader/xlxc924.dat
/usr/share/alsa/firmware/pcxhrloader/xlxint.dat
/usr/share/alsa/firmware/usx2yloader/tascam_loader.ihx
/usr/share/alsa/firmware/usx2yloader/us122.conf
/usr/share/alsa/firmware/usx2yloader/us122.prepad
/usr/share/alsa/firmware/usx2yloader/us122.rbt
/usr/share/alsa/firmware/usx2yloader/us122fw.ihx
/usr/share/alsa/firmware/usx2yloader/us224.conf
/usr/share/alsa/firmware/usx2yloader/us224.prepad
/usr/share/alsa/firmware/usx2yloader/us224.rbt
/usr/share/alsa/firmware/usx2yloader/us224fw.ihx
/usr/share/alsa/firmware/usx2yloader/us428.conf
/usr/share/alsa/firmware/usx2yloader/us428.prepad
/usr/share/alsa/firmware/usx2yloader/us428.rbt
/usr/share/alsa/firmware/usx2yloader/us428fw.ihx
/usr/share/alsa/firmware/vxloader/bd56002.boot
/usr/share/alsa/firmware/vxloader/bd563s3.boot
/usr/share/alsa/firmware/vxloader/bd563v2.boot
/usr/share/alsa/firmware/vxloader/bx_1_vp4.b56
/usr/share/alsa/firmware/vxloader/bx_1_vxp.b56
/usr/share/alsa/firmware/vxloader/l_1_v22.d56
/usr/share/alsa/firmware/vxloader/l_1_vp4.d56
/usr/share/alsa/firmware/vxloader/l_1_vx2.d56
/usr/share/alsa/firmware/vxloader/l_1_vxp.d56
/usr/share/alsa/firmware/vxloader/vx222.conf
/usr/share/alsa/firmware/vxloader/vxboard.conf
/usr/share/alsa/firmware/vxloader/vxp440.conf
/usr/share/alsa/firmware/vxloader/vxpocket.conf
/usr/share/alsa/firmware/vxloader/x1_1_vp4.rbt
/usr/share/alsa/firmware/vxloader/x1_1_vx2.rbt
/usr/share/alsa/firmware/vxloader/x1_1_vxp.rbt
/usr/share/alsa/firmware/vxloader/x1_2_v22.rbt

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/alsa-firmware/COPYING
